### PR TITLE
Fix BC with Symfony 2.8 LTS

### LINKED ISSUE #321: You have requested a non-existent parameter "kernel.project_dir"
Symfony 2.8 LTS

- Updating lexik/translation-bundle (v4.0.9 => v4.0.10): Downloading (100%)  

  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                                                            
  You have requested a non-existent parameter "kernel.project_dir". Did you mean one of these: "kernel.root_dir", "kernel.cache_dir", "kernel.logs_dir"?

I guess at some point older versions of symfony won't be supported.. is this one of those times?

### PR DESCRIPTION
**Pull request by SanderVerkuil**
The parameter `%kernel.project_dir%` is not existent in symfony versions prior to version 3.3. This fix checks whether the parameter `%kernel.project_dir%` exists, otherwise it will use the `%kernel.root_dir%/../` as an alternative.

Fixes #321

### CODE REVIEW

File: DependencyInjection/LexikTranslationExtension.php [hunk 1]
```diff
@@ -138,9 +138,18 @@ public function prepend(ContainerBuilder $container)
             return;
         }
 
+        $rootDir = 'vendor/lexik/translation-bundle/Resources/views';
+
+        // Only symfony versions >= 3.3 include the kernel.project_dir parameter
+        if ($container->hasParameter('kernel.project_dir')) {
```
Comment (spike31) [inline DependencyInjection/LexikTranslationExtension.php]: Maybe it's better to test with `if (Kernel::VERSION_ID >= 30300) {`

Comment (SanderVerkuil) [reply DependencyInjection/LexikTranslationExtension.php]: Will do, forgot that the Symfony version is present as a static kernel variable.

**Comment by spike31** [comment]
Ok let's go!

**Comment by spike31** [comment]
https://github.com/lexik/LexikTranslationBundle/releases/tag/v4.0.11
